apiVersion: v1
kind: Service
metadata:
  name: netology-svc-nodeport
spec:
  selector:
    app: nginx
  ports:
    - name: nginx
      protocol: TCP
      port: 80
      nodePort: 30080
    - name: multitool
      protocol: TCP
      port: 8080
      nodePort: 30880
  type: NodePort
