apiVersion: apps/v1
kind: Deployment
metadata:
  name: busy-multi
  labels:
    app: busy-multi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busy-multi
  template:
    metadata:
      labels:
        app: busy-multi
    spec:
      containers:
        - name: busybox
          image: busybox
          command:
            [
              "sh",
              "-c",
              'while true; do echo "current date = $(date)" >> /output/date.log; sleep 5; done',
            ]
          volumeMounts:
            - mountPath: "/output"
              name: data
        - name: multitool
          image: wbitt/network-multitool
          volumeMounts:
            - name: data
              mountPath: "/output"
      volumes:
        - name: data
          emptyDir: {}
